//curl -X POST http://localhost:3000/loginClient \
//-H "Content-Type: application/json" \
//-d '{"unEmail":"ness@gmail.com", "password":"motdepasse123"}'

###

curl -X DELETE http://localhost:3000/avis/1 \
-D "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJuZXNzQGdtYWlsLmNvbSIsImlhdCI6MTcxMjUzNDM1MywiZXhwIjoxNzEyNTM3OTUzfQ.lFINqIJ7q7FrHdXlKhaNqTYgYDeBs9xDUEBpycitwDQ"

//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJuZXNzQGdtYWlsLmNvbSIsImlhdCI6MTcxMjUzNDM1MywiZXhwIjoxNzEyNTM3OTUzfQ.lFINqIJ7q7FrHdXlKhaNqTYgYDeBs9xDUEBpycitwDQ

//curl -X POST http://localhost:3000/registerClient \
//-H "Content-Type: application/json" \
//-d '{"email":"ness@gmail.com", "nomClient":"NomDuClient", "prenomClient":"PrenomDuClient", "numClient":"0123456789", "password":"motdepasse123"}'


// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6eyJpZENsaWVudCI6MSwiZW1haWwiOiJjbGllbnRAZXhhbXBsZS5jb20iLCJub21DbGllbnQiOiJEb2UiLCJwcmVub21DbGllbnQiOiJKb2huIiwibnVtQ2xpZW50IjoxMjM0NTY3ODkwLCJwYXNzd29yZCI6IiQyYSQxMCRTMEVSWjJtY3dGRG16RlB4ZlZEZHkuZURkdjh5cWoyVHI3MzA3MUsvZUFLcExJVHFndDRSTyJ9LCJpYXQiOjE3MTI1MjQxNjEsImV4cCI6MTcxMjUyNzc2MX0.GE2JpdHJ2wKbINayjTGz8ZR0-stH0FwzakGZxUk0tWA"


//curl -X GET http://localhost:3000/rendezvous \
//-H "Content-Type: application/json" \
//-d '{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6eyJpZENsaWVudCI6MSwiZW1haWwiOiJjbGllbnRAZXhhbXBsZS5jb20iLCJub21DbGllbnQiOiJEb2UiLCJwcmVub21DbGllbnQiOiJKb2huIiwibnVtQ2xpZW50IjoxMjM0NTY3ODkwLCJwYXNzd29yZCI6IiQyYSQxMCRTMEVSWjJtY3dGRG16RlB4ZlZEZHkuZURkdjh5cWoyVHI3MzA3MUsvZUFLcExJVHFndDRSTyJ9LCJpYXQiOjE3MTI1MjQxNjEsImV4cCI6MTcxMjUyNzc2MX0.GE2JpdHJ2wKbINayjTGz8ZR0-stH0FwzakGZxUk0tWA"}'
